<#
.SYNOPSIS
    Collect AgentX workflow metrics from git history and progress logs.
.DESCRIPTION
    Parses git history and progress logs to generate a weekly analytics report.
    Output: docs/analytics/report-YYYY-MM-DD.md
.EXAMPLE
    .\.github\scripts\collect-metrics.ps1
    .\.github\scripts\collect-metrics.ps1 -Since "2026-02-01"
#>

param(
    [string]$Since = (Get-Date).AddDays(-7).ToString("yyyy-MM-dd"),
    [string]$OutputDir = "docs/analytics"
)

$ErrorActionPreference = "Stop"
$today = Get-Date -Format "yyyy-MM-dd"

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "  AgentX Metrics Collection" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "Period: $Since to $today"
Write-Host ""

# Ensure output directory exists
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

# --- Git Metrics ---

Write-Host "Collecting git metrics..." -ForegroundColor Yellow

# Commits this period
$commits = git log --since="$Since" --oneline 2>$null
$commitCount = if ($commits) { ($commits | Measure-Object).Count } else { 0 }

# Issues referenced in commits
$issueRefs = @()
if ($commits) {
    $issueRefs = $commits | Select-String -Pattern '#(\d+)' -AllMatches | 
        ForEach-Object { $_.Matches } | 
        ForEach-Object { $_.Groups[1].Value } | 
        Sort-Object -Unique
}

# Commits per type
$featCount = if ($commits) { ($commits | Select-String -Pattern '^[a-f0-9]+ feat:' | Measure-Object).Count } else { 0 }
$fixCount = if ($commits) { ($commits | Select-String -Pattern '^[a-f0-9]+ fix:' | Measure-Object).Count } else { 0 }
$docsCount = if ($commits) { ($commits | Select-String -Pattern '^[a-f0-9]+ docs:' | Measure-Object).Count } else { 0 }
$testCount = if ($commits) { ($commits | Select-String -Pattern '^[a-f0-9]+ test:' | Measure-Object).Count } else { 0 }
$reviewCount = if ($commits) { ($commits | Select-String -Pattern '^[a-f0-9]+ review:' | Measure-Object).Count } else { 0 }
$otherCount = $commitCount - $featCount - $fixCount - $docsCount - $testCount - $reviewCount

# --- Progress Log Metrics ---

Write-Host "Scanning progress logs..." -ForegroundColor Yellow

$progressLogs = Get-ChildItem -Path "docs/progress/ISSUE-*-log.md" -ErrorAction SilentlyContinue
$totalSessions = 0
$issuesWithLogs = 0

foreach ($log in $progressLogs) {
    $issuesWithLogs++
    $content = Get-Content $log.FullName -Raw
    $sessions = ($content | Select-String -Pattern '## Session \d+' -AllMatches).Matches.Count
    $totalSessions += $sessions
}

$avgSessionsPerIssue = if ($issuesWithLogs -gt 0) { [math]::Round($totalSessions / $issuesWithLogs, 1) } else { 0 }

# --- GitHub Metrics (if gh CLI available) ---

$ghAvailable = $null -ne (Get-Command gh -ErrorAction SilentlyContinue)
$closedIssues = 0
$openIssues = 0
$reworkIssues = 0

if ($ghAvailable) {
    Write-Host "Collecting GitHub metrics..." -ForegroundColor Yellow
    
    try {
        $closedJson = gh issue list --state closed --since "$Since" --json number 2>$null
        if ($closedJson) {
            $closedIssues = ($closedJson | ConvertFrom-Json | Measure-Object).Count
        }

        $openJson = gh issue list --state open --json number 2>$null
        if ($openJson) {
            $openIssues = ($openJson | ConvertFrom-Json | Measure-Object).Count
        }

        $reworkJson = gh issue list --label "needs:changes" --state all --json number 2>$null
        if ($reworkJson) {
            $reworkIssues = ($reworkJson | ConvertFrom-Json | Measure-Object).Count
        }
    } catch {
        Write-Host "  Warning: GitHub API query failed, using defaults" -ForegroundColor Yellow
    }
}

$reworkRate = if ($closedIssues -gt 0) { [math]::Round(($reworkIssues / $closedIssues) * 100, 1) } else { 0 }

# --- Generate Report ---

Write-Host "Generating report..." -ForegroundColor Yellow

$report = @"
# AgentX Weekly Report - Week of $today

> Auto-generated by ``collect-metrics.ps1`` on $today  
> Period: $Since to $today

---

## Summary

| Metric | Value |
|--------|-------|
| **Commits** | $commitCount |
| **Issues Referenced** | $($issueRefs.Count) |
| **Issues Closed** | $closedIssues |
| **Issues Open** | $openIssues |
| **Rework Rate** | $reworkRate% |
| **Progress Logs** | $issuesWithLogs |
| **Total Sessions** | $totalSessions |
| **Avg Sessions/Issue** | $avgSessionsPerIssue |

---

## Commits by Type

| Type | Count |
|------|-------|
| feat | $featCount |
| fix | $fixCount |
| docs | $docsCount |
| test | $testCount |
| review | $reviewCount |
| other | $otherCount |

```mermaid
pie title Commits by Type
    "feat" : $featCount
    "fix" : $fixCount
    "docs" : $docsCount
    "test" : $testCount
    "review" : $reviewCount
    "other" : $otherCount
```

---

## Issues Referenced

$( if ($issueRefs.Count -gt 0) { $issueRefs | ForEach-Object { "- #$_" } | Out-String } else { "No issues referenced in commits this period." } )

---

## Rework Analysis

| Metric | Value | Target |
|--------|-------|--------|
| Rework Rate | $reworkRate% | < 20% |
| Issues with rework | $reworkIssues | - |
| Total reviewed | $closedIssues | - |

---

## Session Analysis

| Metric | Value |
|--------|-------|
| Issues with progress logs | $issuesWithLogs |
| Total sessions recorded | $totalSessions |
| Avg sessions per issue | $avgSessionsPerIssue |

---

## Actions

- [ ] Review any bottlenecks identified above
- [ ] Address high rework rate if > 20%
- [ ] Check issues open > 7 days for blockers

---

*Generated by AgentX Analytics*
"@

$reportPath = Join-Path $OutputDir "report-$today.md"
$report | Set-Content -Path $reportPath -Encoding UTF8

Write-Host ""
Write-Host "=========================================" -ForegroundColor Green
Write-Host "  Report saved: $reportPath" -ForegroundColor Green
Write-Host "=========================================" -ForegroundColor Green
