#!/bin/bash
# Collect AgentX workflow metrics from git history and progress logs.
# Parses git history and progress logs to generate a weekly analytics report.
# Output: docs/analytics/report-YYYY-MM-DD.md
#
# Usage:
#   .github/scripts/collect-metrics.sh
#   .github/scripts/collect-metrics.sh --since 2026-02-01

set -e

# Defaults
OUTPUT_DIR="docs/analytics"
TODAY=$(date +%Y-%m-%d)

# Parse --since flag first, then fall back to positional arg or default
if [ "$1" = "--since" ] && [ -n "$2" ]; then
    SINCE="$2"
else
    SINCE="${1:-$(date -d '7 days ago' +%Y-%m-%d 2>/dev/null || date -v-7d +%Y-%m-%d)}"
fi

# Colors
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

echo -e "${CYAN}=========================================${NC}"
echo -e "${CYAN}  AgentX Metrics Collection${NC}"
echo -e "${CYAN}=========================================${NC}"
echo "Period: $SINCE to $TODAY"
echo ""

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# --- Git Metrics ---

echo -e "${YELLOW}Collecting git metrics...${NC}"

COMMITS=$(git log --since="$SINCE" --oneline 2>/dev/null || true)
COMMIT_COUNT=$(echo "$COMMITS" | grep -c . 2>/dev/null || echo 0)
[ -z "$COMMITS" ] && COMMIT_COUNT=0

# Issues referenced in commits
ISSUE_REFS=""
if [ -n "$COMMITS" ]; then
    ISSUE_REFS=$(echo "$COMMITS" | grep -oP '#\K\d+' | sort -u || true)
fi
ISSUE_REF_COUNT=$(echo "$ISSUE_REFS" | grep -c . 2>/dev/null || echo 0)
[ -z "$ISSUE_REFS" ] && ISSUE_REF_COUNT=0

# Commits per type
FEAT_COUNT=0; FIX_COUNT=0; DOCS_COUNT=0; TEST_COUNT=0; REVIEW_COUNT=0
if [ -n "$COMMITS" ]; then
    FEAT_COUNT=$(echo "$COMMITS" | grep -cP '^[a-f0-9]+ feat:' || echo 0)
    FIX_COUNT=$(echo "$COMMITS" | grep -cP '^[a-f0-9]+ fix:' || echo 0)
    DOCS_COUNT=$(echo "$COMMITS" | grep -cP '^[a-f0-9]+ docs:' || echo 0)
    TEST_COUNT=$(echo "$COMMITS" | grep -cP '^[a-f0-9]+ test:' || echo 0)
    REVIEW_COUNT=$(echo "$COMMITS" | grep -cP '^[a-f0-9]+ review:' || echo 0)
fi
OTHER_COUNT=$((COMMIT_COUNT - FEAT_COUNT - FIX_COUNT - DOCS_COUNT - TEST_COUNT - REVIEW_COUNT))
[ "$OTHER_COUNT" -lt 0 ] && OTHER_COUNT=0

# --- Progress Log Metrics ---

echo -e "${YELLOW}Scanning progress logs...${NC}"

ISSUES_WITH_LOGS=0
TOTAL_SESSIONS=0

for log in docs/progress/ISSUE-*-log.md; do
    [ -f "$log" ] || continue
    ISSUES_WITH_LOGS=$((ISSUES_WITH_LOGS + 1))
    sessions=$(grep -c '## Session' "$log" 2>/dev/null || echo 0)
    TOTAL_SESSIONS=$((TOTAL_SESSIONS + sessions))
done

if [ "$ISSUES_WITH_LOGS" -gt 0 ]; then
    AVG_SESSIONS=$(echo "scale=1; $TOTAL_SESSIONS / $ISSUES_WITH_LOGS" | bc 2>/dev/null || echo "0")
else
    AVG_SESSIONS="0"
fi

# --- GitHub Metrics (if gh CLI available) ---

CLOSED_ISSUES=0
OPEN_ISSUES=0
REWORK_ISSUES=0

if command -v gh &> /dev/null; then
    echo -e "${YELLOW}Collecting GitHub metrics...${NC}"

    CLOSED_ISSUES=$(gh issue list --state closed --json number --jq 'length' 2>/dev/null || echo 0)
    OPEN_ISSUES=$(gh issue list --state open --json number --jq 'length' 2>/dev/null || echo 0)
    REWORK_ISSUES=$(gh issue list --label "needs:changes" --state all --json number --jq 'length' 2>/dev/null || echo 0)
fi

if [ "$CLOSED_ISSUES" -gt 0 ]; then
    REWORK_RATE=$(echo "scale=1; ($REWORK_ISSUES * 100) / $CLOSED_ISSUES" | bc 2>/dev/null || echo "0")
else
    REWORK_RATE="0"
fi

# --- Format issue list ---

ISSUE_LIST=""
if [ -n "$ISSUE_REFS" ]; then
    ISSUE_LIST=$(echo "$ISSUE_REFS" | sed 's/^/- #/')
else
    ISSUE_LIST="No issues referenced in commits this period."
fi

# --- Generate Report ---

echo -e "${YELLOW}Generating report...${NC}"

REPORT_PATH="$OUTPUT_DIR/report-$TODAY.md"

cat > "$REPORT_PATH" <<REPORT_EOF
# AgentX Weekly Report - Week of $TODAY

> Auto-generated by \`collect-metrics.sh\` on $TODAY
> Period: $SINCE to $TODAY

---

## Summary

| Metric | Value |
|--------|-------|
| **Commits** | $COMMIT_COUNT |
| **Issues Referenced** | $ISSUE_REF_COUNT |
| **Issues Closed** | $CLOSED_ISSUES |
| **Issues Open** | $OPEN_ISSUES |
| **Rework Rate** | ${REWORK_RATE}% |
| **Progress Logs** | $ISSUES_WITH_LOGS |
| **Total Sessions** | $TOTAL_SESSIONS |
| **Avg Sessions/Issue** | $AVG_SESSIONS |

---

## Commits by Type

| Type | Count |
|------|-------|
| feat | $FEAT_COUNT |
| fix | $FIX_COUNT |
| docs | $DOCS_COUNT |
| test | $TEST_COUNT |
| review | $REVIEW_COUNT |
| other | $OTHER_COUNT |

\`\`\`mermaid
pie title Commits by Type
    "feat" : $FEAT_COUNT
    "fix" : $FIX_COUNT
    "docs" : $DOCS_COUNT
    "test" : $TEST_COUNT
    "review" : $REVIEW_COUNT
    "other" : $OTHER_COUNT
\`\`\`

---

## Issues Referenced

$ISSUE_LIST

---

## Rework Analysis

| Metric | Value | Target |
|--------|-------|--------|
| Rework Rate | ${REWORK_RATE}% | < 20% |
| Issues with rework | $REWORK_ISSUES | - |
| Total reviewed | $CLOSED_ISSUES | - |

---

## Session Analysis

| Metric | Value |
|--------|-------|
| Issues with progress logs | $ISSUES_WITH_LOGS |
| Total sessions recorded | $TOTAL_SESSIONS |
| Avg sessions per issue | $AVG_SESSIONS |

---

## Actions

- [ ] Review any bottlenecks identified above
- [ ] Address high rework rate if > 20%
- [ ] Check issues open > 7 days for blockers

---

*Generated by AgentX Analytics*
REPORT_EOF

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  Report saved: $REPORT_PATH${NC}"
echo -e "${GREEN}=========================================${NC}"
